#+TITLE: On the Gröbner-basis-based Cryptanalysis of Symmetric Primitives: a Tutorial


* 1) Basics of Python/SAGE
See the notes for the exercise session of Monday, in particular the section on
[[https://github.com/lpp-crypto/FSE2025-spring-school/tree/main/BF-Exercises#41-dealing-with-finite-fields-in-sage][dealing with finite fields]].

When writing a script, be sure to include =from sage.all import *= at the top!

** 1.1) Univariate polynomials
Here is how you can generate a univariate polynomial in a finite field of size =q=.
#+BEGIN_SRC python
q = 17 # for example
gf = GF(q)
X = gf.polynomial_ring("X").gen()
pol = X**3+X
print( pol )
print( pol( gf(3) ) )
print( pol( gf(21) ) )
#+END_SRC

Note a difference from the $q = 2^n$ case we saw before: the =fetch_int= method is replaced by the "call" function of the finite field (i.e., we use the finite field instance like a normal python function). Doing this with a finite field of small characteristic is a bad idea: =gf(x)= is the finite field element corresponding to =x % q=: particularly fun in characteristic 2...

** 1.2) Duck typing
Python uses /duck typing/ ("if it walks like a duck and quacks like a duck, then it's probably a duck"); meaning that there is no real type check: if the input to a function provides an interface that allows it to be processed, then the execution carries on.

For example, consider the following basic function.

#+BEGIN_SRC python
def cube(x):
    return x**3
#+END_SRC

The output of =cube(3)= should be easy to guess, however, what happens if you give as in put:
- a string, say ="bla"= ? It fails: the operation ="bla"**3= is not defined.
- the generator of a polynomial ring, so the =X= defined above? It works! =X**3= is defined, so it returns it.

* 2) The univariate case
** 2.1) The MiMC block cipher
MiMC (pronounced like "meme C") is a simple block cipher defined over $F_q$: its round function is simply x \rightarrow (x+k_i)^d. In what follows, we consider a variant we will call miniMiMC. It is defined for any field size q, has both plaintext and master key taken from $F_q$, and then uses the following:
- the subkeys are such that $k_i = K+i$, where $K$ is the master key, and where the first round is round 0;
- d is the smallest integer such that x^d is a non-linear bijective monomial; and
- the number of rounds is the smallest integer $R$ such that $d^R > q$.

- Q? (1) :: Implement MiMC over $F_p$, where $p=2^{12}-5$, and $d=3$. 

  If your implementation of =MiMC(plaintext, master_key)= is correct, then:
  - =MiMC(0, 0) == 3604=
  - =MiMC(1, 0) = 239=
  - =MIMC(0, 2) = 1198=

** 2.2) Generating polynomials
Add the following to the start of your script.

#+BEGIN_SRC python
p = 2**12-5
F = GF(p)
X = F.polynomial_ring("X").gen()
#+END_SRC

- Q? (2) :: What happens if you call =MiMC(X, 2)=? If it doesn't return a polynomial, then amend your implementation of MiMC for it to work. Hint: don't rely on modulo operation, but instead assume your input is a finite finite field element.

** 2.3) Generating polynomial generators
In practice, AO primitives are usually defined for a lot of field sizes. Then, depending on the field size, different parameters are set (here, the exponent). It is then convenient to use /object oriented programming/.

#+BEGIN_SRC python
class miniMiMC:
    def __init__(self, field_size):
        self.exponent = <something>
        self.number_of_rounds = <something>
        self.field    = GF(field_size)

    def round_function(self, x, ki):
        return (x + ki)**self.exponent

    def encrypt(self, plaintext, master_key):
        x = plaintext
        for i in range(0, self.number_of_rounds):
            x = self.round_function(x, master_key + i)
        return x

    def decrypt(self, ciphertext, master_key):
        return <something>
#+END_SRC

- Q? (3) :: fill in the =<something>= in the program above. Hint: the multiplicative inverse of =x= modulo =n= is given by the SAGE function =inverse_mod(x, n)=.
  
As you can see, there is no modulus operation: it will not work if the inputs are not of the correct type!

This class allows you to write code like the following.

#+BEGIN_SRC python
for p in [2**12-5, 2**31-1]:
    print("--", p)
    E_k = miniMiMC(p)
    print(E_k.number_of_rounds) # there is no notion of protected
                                # attribute in python
    y = E_k.encrypt(0, 0)
    print(y, E_k.decrypt(y, 0))
#+END_SRC

** 2.4) Basic algebraic attack
Let's tweak your implementation of miniMiMC even more. Python (and thus, SAGE) allow optional arguments in functions, including in function constructors. This is achieved using the following syntax.

#+BEGIN_SRC python
def some_function(x, y, potential_parameter=0):
    return x + y + potential_parameter
#+END_SRC

We then have that =some_function(1, 2)= is 3, but =some_function(1,2, potential_parameter=2)= is 5.

- Q? (4) :: modify the =miniMiMC= class so the constructor accepts an optional number of rounds. Use it to print the univariate representation of miniMiMC(x) reduced to 3 rounds for various keys.

- Q? (5) :: nothing prevents us from putting the polynomial variable in the key, and have the plaintext be a constant. Print some such polynomials, again for 3-round miniMiMC. To be fancy, use a variable called =K= instead of =X=.

- Q? (6) :: write a small function that takes as input a master key =K= and returns a handful of plaintext/ciphertext pairs corresponding to miniMiMC encryptions under key =K=.

- Q? (7) :: write another function that takes a =list= of such plaintext/ciphertext pairs and returns equations that the master key needs to satisfy, one per pair.

The key then is the =.roots()= method of a polynomial in SAGE. The following trivial example shows how it works.

#+BEGIN_SRC python
X = GF(2**31-1).polynomial_ring("X").gen()
pol = X**2 - X
print(pol.roots())
pol = (X-1) * (X-2) * (X-17)**3
print(pol.roots())
#+END_SRC

As you can see, =.roots()= returns a list of tuples where the first element is a root of the polynomial, and the second its multiplicity.

- Q? (8) :: Write a function that, given only some plaintext/ciphertext pairs obtained using a round-reduced miniMiMC encryption, returns the secret =K=. Start with a low number of rounds for a proof of concept, and then see how far you can go!

* 3) The multivariate case
** 3.1) Declaring a system of multivariate equations
For more information, head over to the [[https://doc.sagemath.org/html/en/reference/polynomial_rings/sage/rings/polynomial/multi_polynomial_ideal.html][sage documentation]].

We first need to declare the ring of polynomials in the variables we want, over the field we are interested. While the =polynomial_ring= method of the =GF= class can work, it lacks some features (in particular, the choice of monomial ordering).

Instead, we directly use the class =PolynomialRing=. It is initialized with a field, and a list of variable names, as shown below. Note the use of =.gens()= with a =s= instead of =.gen()= since there are multiple generators!

#+BEGIN_SRC python
F = GF(2**12-5)
X, Y = PolynomialRing(F, ["X", "Y"]).gens()
print(X, Y)
print(X*Y**2 + X + 3*Y + 2)
#+END_SRC

Since the input we give to the =polynomial_ring= is simply a list of strings corresponding to the names of the variables, we can build one by hand. Run the following commands:

#+BEGIN_SRC python
F = GF(2**12-5)
polynomial_unknowns_names = []
for i in range(0, 3):
    polynomial_unknowns_names.append("X_" + str(i))
X = PolynomialRing(F, polynomial_unknowns_names).gens()
print(X)
for i in range(0, len(X)):
    print("var number ", i, " =", X[i])
#+END_SRC

or the following one if you prefer to show of with python one-liners.

#+BEGIN_SRC python
F = GF(2**12-5)
X = PolynomialRing(F,
                   ["X_{}".format(i) for i in range(0, 3)]
                   ).gens()
print(X)
#+END_SRC

It is then easy to write-down a system of multivariate equations, or rather, a list of multivariate polynomials that are intended to be equal to 0:

#+BEGIN_SRC python
F = GF(2**12-5)
X = PolynomialRing(F,
                   ["X_{}".format(i) for i in range(0, 4)]
                   ).gens()
system_of_equations = [
    X[0]**3 * X[1] + X[2] - 2, 
    X[1]**2 + X[3] - 3,
    X[0] + X[1] + X[2]**3 + X[3] - 4,
    X[0] + X[1]*X[2]*X[3] - 1
]
#+END_SRC

We can then generate the ideal generated by this system of equations in the most straightforward way.

#+BEGIN_SRC python
I = ideal(system_of_equations)
#+END_SRC

This object then has useful methods:

#+BEGIN_SRC python
I.groebner_basis()    # returns a list of polynomials corresponding to
                      # the Gröbner basis of I for a specific ordering
len(I.normal_basis()) # returns the ideal degree D_I
I.variety()           # returns the content of the variety of I, i.e.,
                      # in practice, the solutions of the system of
                      # equations
#+END_SRC

Finally, it is possible to change the monomial ordering, but this has to be done when setting up the =PolynomialRing= instance:

#+BEGIN_SRC python
X = PolynomialRing(F,
                   ["X_{}".format(i) for i in range(0, 3)],
                   order="lex" # <----- where the magic happens
                   ).gens()
#+END_SRC

The value of =order= can then be one of several things, among which:
- ="lex"= for lexicographic ordering,
- ="deglex"= for an ordering that sorts first the terms by overall degree, and then in lexicographic order,
- ="degrevlex"= the same but with reversed lexicographic ordering,
- all of these are shortcuts to build the correct =TermOrder= instance, for which the documentation is [[https://doc.sagemath.org/html/en/reference/polynomial_rings/sage/rings/polynomial/term_order.html][here]].

- Q? (9) :: What is the length of the Gröbner basis of this ideal for ="lex"= (lexicographic ordering)?

- Q? (10) :: It is possible to change the monomial ordering at the construction of the =PolynomialRing= instance by adding the argument =order = "lex"= (or any other valid ordering). What is the length of the Gröbner basis for different ordering? What is the degree of the polynomials in them?

- Q? (11) :: In SAGE, the ideal degree D_I is given by the length of the "normal basis": =len(I.normal_basis())=. How does the ideal degree change when the ordering of the polynomial changes?

** 3.2) Custom Ordering
We can also build a custom graded monomial ordering by giving weights to the different variables.

#+BEGIN_SRC python
w0 = 1 # the weight to give to X_0
w1 = 1 # the weight to give to X_1
w2 = 1 # etc
w3 = 1 # etc

weighted_ordering = TermOrder("wdeglex", # <-- note the "w" for "weighted"!
                              [w0, w1, w2, w3])

X = PolynomialRing(F,
                   ["X_{}".format(i) for i in range(0, 3)],
                   order=weighted_ordering,
                   ).gens()
#+END_SRC

- Q? (12) :: Answer questions 9-10-11 using monomial orderings with custom weights. For example, try to give a very high weight to one variable and not to the others: what happens then? Does the high-weight term appear often in the Groebner basis corresponding to this monomial ordering?

* 4) Attacking a toy primitive
** 4.1) "SPeciFicATion"
=Cobaye= is a permutation allowing an efficient low degree arithmetization of their verification. It is defined for any prime =p > 2**6=, and operates as follows.

- interface :: =Cobaye= operates on =t= branches where =t= is at least 4, at most 10, and must be even.
- round function :: =Cobaye= uses a Generalized Feistel Network structure, combined with a diffusion layer.

  1. The GFN is denoted G_d and has a simple structure: for a vector x of length t of elements of F_p, it operates as follows.

     G(x_0, ..., x_{t-1}) = (y_0, ..., y_{t-1}), with
     + y_0 = x_0
     + y_1 = x_1+x_0^{1/d}
     + y_i = x_i+y_{i-1}^2, for all i>1.
       Of course, d is the smallest non-linear bijective exponent.

  2. The linear layer L operates by iterating the following linear Feistel round L 2t times:

     L(x_0, ..., x_{t-1}) = (y_0, ..., y_{t-1}), with
     + y_i = x_{i+1} for i<t-1
     + y_{t-1} = x_0 + x_{t-1} 
        
- reference implementation :: A reference implementation in C++ [1] that is unlikely to compile properly is provided below. 

Some small hints for this section:
- obviously, write clean code from the start so you can make sure that your equations are correct;
- don't use a large value for =p=: it needlessly slows down computations, and may make the output harder to read;
- choose =p= carefully to make sure that =d=3=, so that the equations are simpler.
    
#+BEGIN_SRC C++
class Cobaye_Permutation
{
private:
    unsigned int p;
    unsigned int t;
    unsigned int r;
    unsigned int d;
    unsigned int d_inv;
    unsigned long int cstte ;

public:
    Cobaye_Permutation(
        unsigned int _p,
        unsigned int _t,
        unsigned int _d
        ) : p(_p), t(_t), d(_d), d_inv(2), cstte(1) {
        // stupid computation of d_inv
        while ((d * d_inv) % p != 1)
            d_inv ++ ;
    };

    long int get_constant()
    {
        cstte = (32*cstte) % p ;
        return cstte;
    };


    void cobaye_permutation(std::vector<long int> x) 
    {
        if (x.size() != t)
            throw std::runtime_error("wrong length of x");
        else
        {
            unsigned int t = x.size();
            for(unsigned int i=0; i<r; i++)
            {
                // GFN layer
                x[1] = (x[1] + pow_mod(x[0], d_inv, p)) % p;
                for(unsigned int j=2; j<t; j+=1)
                    x[j]   = (x[j] + x[j-1]*x[j+1]) % p; // squares
                // L layer, consisting of 2t linear Feistel rounds
                for(unsigned l=0; l < 2*t; l++)
                {
                    long int tmp = (x[0] + x[t-1]) % p;
                    for(unsigned int j=0; j<t-1; j++)
                        x[j] = x[j+1];
                    x[t-1] = tmp;
                }
                // add constant
                for(unsigned int j=0; j<t; j++)
                    x[j] = (x[j] + cstte) % p;
            }
        }
        return x;
    };
}

#+END_SRC

** 4.2) Questions
The question we are trying to answer is the following:

#+BEGIN_QUOTE
How does the degree of the ideal scale with the number of branches =t= and with the number of rounds =r=?
#+END_QUOTE

Indeed, recall that that D_I is the quantity we should base security arguments on, so we want to know what its value is---or at least try to estimate it.

- Q? (13) :: Implement the round function of =Cobaye= in SAGE.
- Q? (14) :: Implement the generation of the equations corresponding to the *verification* of =Cobaye=. Test them against the round function to check if actual input.output pairs satisfy the equations.
- Q? (15) :: Try and estimate the value of D_I by asking SAGE to compute the size of the normal basis using the ="lex"= Groebner basis. How far can you go in terms of number of rounds and number of branches? No need to let it run for a long time, say more than 1min. If it is too slow for some parameters then you have your answer.
- Q? (16) :: Design a weighted ordering that will allow you to get the Groebner basis for free, then implement it in SAGE. You use SAGE to test if it is indeed a Groebner basis (asking it to compute the Groebner basis of the ideal will be instantaneous if your ordering is correct since it does not need to do anything.
- Q? (17) :: How does the degree of the ideal scale with the number of branches =t= and with the number of rounds =r=?

* Footnotes

[1] Why not in SAGE? Because I had to suffer through reference implementations in Rust, so you have to suffer too :P

